//@version=2

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//                                                 //                                                             //

//██████╗ ██╗ ██████╗ ███╗   ███╗ █████╗ ████████╗ // ████████╗██████╗ ███████╗███╗   ██╗██████╗ ███████╗██████╗  //

//██╔══██╗██║██╔════╝ ████╗ ████║██╔══██╗╚══██╔══╝ // ╚══██╔══╝██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔════╝██╔══██╗ //

//██████╔╝██║██║  ███╗██╔████╔██║███████║   ██║    //    ██║   ██████╔╝█████╗  ██╔██╗ ██║██║  ██║█████╗  ██████╔╝ //

//██╔══██╗██║██║   ██║██║╚██╔╝██║██╔══██║   ██║    //    ██║   ██╔══██╗██╔══╝  ██║╚██╗██║██║  ██║██╔══╝  ██╔══██╗ //

//██████╔╝██║╚██████╔╝██║ ╚═╝ ██║██║  ██║   ██║    //    ██║   ██║  ██║███████╗██║ ╚████║██████╔╝███████╗██║  ██║ //

//╚═════╝ ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝    //    ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═════╝ ╚══════╝╚═╝  ╚═╝ //

//                                                 //                                                             //

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//                     Totally Open Source, built by BigMat. I was inspired by works such as:                     //  

//                                     "TrendRider" by "TradeCiety", Rolf S.                                      //  

//                            "Setup Tabajara" by "Ogro de Wall Street", André Machado                            //  



study(title = "Trender", shorttitle = "Trender", overlay = true)



//                                          ███████╗███╗   ███╗ █████╗                                            //   

//                                          ██╔════╝████╗ ████║██╔══██╗                                           //  

//                                          █████╗  ██╔████╔██║███████║                                           //  

//                                          ██╔══╝  ██║╚██╔╝██║██╔══██║                                           // 

//                                          ███████╗██║ ╚═╝ ██║██║  ██║                                           //  

//                                          ╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝                                           //  

// INPUT EMA 1

ema_background_1 = input(true, title = "Show EMA background color.")

show_ema_1 = input(false, title = "Show EMA.")

// PLOTTED EMA 1

per_ema1 = input(27, minval = 1, title = "EMA Period")

src_ema1 = input(close, title = "Source")

ema1 = ema(src_ema1, per_ema1)



ema_Color_1 = ema1 > ema1[1] and close > ema1 ? green : ema1 < ema1[1] and close < ema1 ? red : yellow

plot( show_ema_1 ? ema1 : na, color = ema_Color_1, style = line, title = "EMA 1", linewidth = 1)



// INPUT EMA 2

show_ema_2 = input(false, title = "Show EMA 2.")

// PLOTTED EMA 2

per_ema2 = input(9, minval = 1, title = "EMA 2 Period")

src_ema2 = input(close, title = "Source")

ema2 = ema(src_ema2, per_ema2)



ema_Color_2 = ema2 > ema2[1] and close > ema2 ? green : ema2 < ema2[1] and close < ema2 ? red : yellow

plot( show_ema_2 ? ema2 : na, color = ema_Color_2, style = line, title = "EMA 2", linewidth = 1)



// INPUT EMA 3

show_ema_3 = input(false, title = "Show EMA 3.")

